Repository buggregator/server, pull requests merged in 2023-12, with the labels that each got.

#101 Optimize JSON encoding
  app/src/Application/Broadcasting/BroadcastEventInterceptor.php
Labels: bug, module [var-dump]

#104 Covers var-dumper handler with tests
  tests/Feature/Interfaces/Http/ControllerTestCase.php
  tests/Feature/Interfaces/TCP/TCPTestCase.php
  tests/Feature/Interfaces/TCP/VarDumper/SymfonyV6Test.php
  tests/Feature/Interfaces/TCP/VarDumper/SymfonyV7Test.php
  tests/TestCase.php
Labels: enhancement, module [Core]

#105 Adds Swagger API docs
  app/config/swagger.php
  app/modules/Events/Interfaces/Http/Controllers/ClearAction.php
  app/modules/Events/Interfaces/Http/Controllers/DeleteAction.php
  app/modules/Events/Interfaces/Http/Controllers/ListAction.php
  app/modules/Events/Interfaces/Http/Controllers/ShowAction.php
  app/modules/Events/Interfaces/Http/Request/ClearEventsRequest.php
  app/modules/Events/Interfaces/Http/Resources/EventResource.php
  app/src/Application/Bootloader/RoutesBootloader.php
  app/src/Application/HTTP/Response/SuccessResource.php
  app/src/Application/Kernel.php
  composer.json
Labels: documentation, enhancement, module [Core]

#109 Small fixes
  .github/workflows/docker-image.yml
  .rr-prod.yaml
  app/src/Application/Bootloader/AttributesBootloader.php
  app/src/Application/Kernel.php
Labels: bug

#110 Adds an ability to remove events by uuids
  app/modules/Events/Interfaces/Commands/ClearEventsHandler.php
  app/modules/Events/Interfaces/Http/Controllers/ClearAction.php
  app/modules/Events/Interfaces/Http/Request/ClearEventsRequest.php
  app/src/Application/Commands/ClearEvents.php
  app/src/Application/Persistence/CacheEventRepository.php
  tests/App/Events/EventsMocker.php
  tests/App/Http/HttpFaker.php
  tests/Feature/Interfaces/Http/Events/ClearActionTest.php
  tests/Feature/Interfaces/Http/Inspector/InspectorActionTest.php
  tests/Feature/Interfaces/Http/Ray/AvailabilityCheckActionTest.php
  tests/Feature/Interfaces/Http/Ray/LocksActionTest.php
  tests/Feature/Interfaces/Http/Ray/RayActionTest.php
  tests/Feature/Interfaces/Http/Sentry/SentryV3ActionTest.php
  tests/Feature/Interfaces/Http/Sentry/SentryV4ActionTest.php
  tests/Feature/Interfaces/TCP/VarDumper/SymfonyV6Test.php
  tests/Feature/Interfaces/TCP/VarDumper/SymfonyV7Test.php
  tests/Unit/Modules/Events/Domain/CacheEventRepositoryTest.php
Labels: enhancement, module [Events]

#112 Fixes problem with detecting HTTP dump request via HTTP user
  app/modules/HttpDumps/Interfaces/Http/Handler/AnyHttpRequestDump.php
  app/modules/Ray/Interfaces/Http/Handler/EventHandler.php
  tests/App/Http/HttpFaker.php
  tests/Feature/Interfaces/Http/HttpDumps/HttpDumpsActionTest.php
  tests/Feature/Interfaces/Http/Inspector/InspectorActionTest.php
  tests/Feature/Interfaces/Http/Ray/RayActionTest.php
  tests/Feature/Interfaces/Http/Sentry/SentryV3ActionTest.php
Labels: module [Http-dump]

#117 Fixes problem with parsing request payload with gzip content-type
  app/modules/Sentry/Application/PayloadParser.php
  app/modules/Sentry/Interfaces/Http/Handler/EventHandler.php
  app/src/Application/Bootloader/RoutesBootloader.php
  app/src/Application/HTTP/Middleware/JsonPayloadMiddleware.php
  tests/Feature/Interfaces/Http/Sentry/SentryV4ActionTest.php
Labels: bug, module [Sentry]
