Repository buggregator/server, pull requests merged in 2023-05, with the labels that each got.

#37 Fixes problem with displaying SMTP emails
  frontend/components/SmtpPage/SmtpPage.vue
  frontend/components/SmtpPagePreview/SmtpPagePreview.vue
  frontend/pages/smtp/[id].vue
Labels: bug, ui:bug

#38 Adds the ability to download smtp email attachments
  app/config/distribution.php
  app/config/storage.php
  app/modules/Smtp/Application/Mail/Message.php
  app/modules/Smtp/Application/Mail/Parser.php
  app/modules/Smtp/Interfaces/Http/Controllers/DownloadAttachmentAction.php
  app/modules/Smtp/Interfaces/TCP/Service.php
  app/src/Application/Kernel.php
  frontend/components/SmtpAttachment/SmtpAttachment.stories.ts
  frontend/components/SmtpAttachment/SmtpAttachment.vue
  frontend/components/SmtpPage/SmtpPage.vue
  frontend/config/types.ts
  frontend/mocks/smtp-welcome.json
Labels: enhancement

#40 Added XHProfLink, fix links
  frontend/components/PagePlaceholder/PagePlaceholder.vue
Labels: enhancement

#51 Add missing space in readme
  README.md
Labels: bug, documentation
