Repository buggregator/server, pull requests merged in 2024-08, with the labels that each got.

#239 Update `spiral/roadrunner-bride` package version
  app/src/Interfaces/Http/Controller/Auth/LoginAction.php
  composer.lock
  rector.php
Labels: c: easy, module [Core]

#240 Reverted Dolt DB back to the previous stable version `1.42.8`
  .docker/Dockerfile
  app/modules/Events/Interfaces/Commands/DeleteEventHandler.php
  bin/get-binaries.sh
Labels: bug, database [mysql]

#244 Add platform detection to get-binaries.sh
  bin/get-binaries.sh
Labels: enhancement

#245 Fix makefile to run server locally
  Makefile
Labels: bug
