Repository buggregator/server, pull requests merged in 2024-04, with the labels that each got.

#125 Added functionality to configure external databases for event storage
  .env.sample
  app/config/database.php
  app/src/Application/Bootloader/PersistenceBootloader.php
  app/src/Application/Persistence/MongoDBEventRepository.php
  docker/Dockerfile
  docker/entrypoint.sh
Labels: enhancement

#122 Add support for Auth0 user authentication
  app/src/Application/Auth/AuthSettings.php
  app/src/Application/Auth/JWTTokenStorage.php
  app/src/Application/Auth/SuccessRedirect.php
  app/src/Application/Auth/Token.php
  app/src/Application/Bootloader/AuthBootloader.php
  app/src/Application/Bootloader/RoutesBootloader.php
  app/src/Application/HTTP/Response/UserResource.php
  app/src/Application/Kernel.php
  app/src/Application/OAuth/ActorProvider.php
  app/src/Application/OAuth/SessionStore.php
  app/src/Application/OAuth/User.php
  app/src/Interfaces/Centrifugo/RPCService.php
  app/src/Interfaces/Http/Controller/Auth/CallbackAction.php
  app/src/Interfaces/Http/Controller/Auth/LoginAction.php
  app/src/Interfaces/Http/Controller/Auth/MeAction.php
  app/src/Interfaces/Http/Controller/GetVersionAction.php
  app/src/Interfaces/Http/Controller/SettingsAction.php
  composer.json
Labels: enhancement, c: medium, module [Core]

#127 Bugfixes
  app/modules/Smtp/Interfaces/TCP/Service.php
  app/src/Application/OAuth/ActorProvider.php
  app/src/Interfaces/Centrifugo/RPCService.php
  app/src/Interfaces/Http/Handler/FrontendRequest.php
  docker/Dockerfile
Labels: bug, module [Core], module [Smtp]

#131 Bugfixes
  app/modules/Smtp/Interfaces/Http/Controllers/DownloadAttachmentAction.php
  app/src/Application/Auth/JWTTokenStorage.php
  app/src/Application/Bootloader/RoutesBootloader.php
  app/src/Application/OAuth/SessionStore.php
Labels: bug, module [SSO]

#136 Maintenance/php82 min
  app/src/Application/Bootloader/PersistenceBootloader.php
  app/src/Application/Persistence/DriverEnum.php
Labels: bug, database [pgsql]

#138 Fixes problem with stuck auth session
  app/src/Application/Bootloader/AuthBootloader.php
Labels: bug, module [SSO]

#145 Reduce size of var-dumper dump payload.
  app/modules/VarDumper/Application/Dump/BodyInterface.php
  app/modules/VarDumper/Application/Dump/DumpIdGeneratorInterface.php
  app/modules/VarDumper/Application/Dump/HtmlBody.php
  app/modules/VarDumper/Application/Dump/HtmlDumper.php
  app/modules/VarDumper/Application/Dump/MtRandDumpIdGenerator.php
  app/modules/VarDumper/Application/Dump/PrimitiveBody.php
  app/modules/VarDumper/Application/VarDumperBootloader.php
  app/modules/VarDumper/Interfaces/TCP/Service.php
  app/src/Application/Kernel.php
  phpunit.xml
  tests/Feature/Interfaces/TCP/VarDumper/SymfonyV7Test.php
Labels: enhancement, module [var-dump]

#146 feat: add ability to set IDE url template
  app/src/Application/AppVersion.php
  app/src/Application/Bootloader/AppBootloader.php
  app/src/Application/Ide/UrlTemplate.php
  app/src/Interfaces/Http/Controller/SettingsAction.php
Labels: c: easy, module [Core], usability

#162 Add register modules sequence command.
  .docker/Dockerfile
  .rr-prod.yaml
  .rr.yaml
  Makefile
  app/modules/Metrics/Application/MetricsBootloader.php
  app/modules/Projects/Application/ProjectBootloader.php
  app/modules/Webhooks/Application/WebhooksBootloader.php
  app/src/Application/Mode.php
  app/src/Interfaces/Console/RegisterModulesCommand.php
  app/src/Interfaces/Console/TestCommand.php
  composer.json
  composer.lock
Labels: module [Core]

#163 Adds missed `migrate` command to `reqister:modules` sequence
  app/src/Application/Bootloader/PersistenceBootloader.php
  tests/App/Console/SpyConsoleInvoker.php
  tests/Feature/Interfaces/Console/RegisterModulesTest.php
  tests/TestCase.php
Labels: bug, enhancement

#165 Adds an ability to send var-dumper dumps with specifying language for code highlighting.
  app/modules/Ray/Application/Handlers/RemoveSfDumpScriptHandler.php
  app/modules/Ray/Application/RayBootloader.php
  app/modules/VarDumper/Interfaces/TCP/Service.php
  tests/Feature/Interfaces/Http/Ray/RayActionTest.php
  tests/Feature/Interfaces/TCP/VarDumper/SymfonyV7Test.php
Labels: enhancement, c: easy, module [var-dump], performance
